name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x']

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
     
      - name: Build
        run: | 
          cd ./workshop-service
          go build
          
      # - name: Build
      #   run: |
      #     ls
      #     go build 
          
      # - name: Test with the Go CLI
      #   run: go test -json > TestResults-${{ matrix.go-version }}.json

      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Go-results-${{ matrix.go-version }}
      #     path: TestResults-${{ matrix.go-version }}.json

      